//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.EdmundsApi.Resources {
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseUrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal BaseUrls() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clients.EdmundsApi.Resources.BaseUrls", typeof(BaseUrls).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://api.edmunds.com/api/vehicle/v2/styles/{0}/engines.
        /// </summary>
        public static string EnginesUrl {
            get {
                return ResourceManager.GetString("EnginesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://api.edmunds.com/api/vehicle/v2/makes.
        /// </summary>
        public static string MakesUrl {
            get {
                return ResourceManager.GetString("MakesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://api.edmunds.com/api/vehicle/v2/{0}/models.
        /// </summary>
        public static string ModelsUrl {
            get {
                return ResourceManager.GetString("ModelsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://api.edmunds.com/api/vehicle/v2/styles/{0}.
        /// </summary>
        public static string StylesUrl {
            get {
                return ResourceManager.GetString("StylesUrl", resourceCulture);
            }
        }
    }
}
